apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-cluster-demo.fullname" . }}-dbsecrets
  namespace: {{ $.Release.Namespace }}
data:
  {{- $name := printf "%s-dbsecrets" ( include "mongodb-cluster-demo.fullname" . ) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace $name).data }}
  {{- if $secret }}
  # Secret exists: 
  {{- toYaml $secret | nindent 2 }}
  {{ else }}
  dbaPassword: {{ randAlphaNum 20 | b64enc }}
  userPassword: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-cluster-demo.fullname" . }}-keys
  namespace: {{ $.Release.Namespace }}
data:
  {{- $name := printf "%s-keys" ( include "mongodb-cluster-demo.fullname" . ) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace $name).data }}
  {{- if $secret }}
  # Secret exists: 
  {{- toYaml $secret | nindent 2 }}
  {{ else }}
  key1: {{ randAlphaNum 756 | b64enc }}
  {{- end }}