apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-cluster-demo.fullname" . }}-dbsecrets
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{- $name := printf "%s-dbsecrets" ( include "mongodb-cluster-demo.fullname" . ) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace $name).data }}
  {{- if $secret }}
  # Secret exists: 
  {{- toYaml $secret | nindent 2 }}
  # $secret.dbaPassword: {{- $secret.dbaPassword }}
  {{- $_ := set $ "dbaPassword" $secret.dbaPassword }}
  # $.dbaPassword: {{- $.dbaPassword }}
  # $secret.monitoringPassword: {{- $secret.monitoringPassword }}
  {{- $_ := set $ "monitoringPassword" $secret.monitoringPassword }}
  # $.monitoringPassword: {{- $.monitoringPassword }}
  {{ else }}
  {{- $dbaPassword := randAlphaNum 32 | b64enc }}
  {{- $_ := set $ "dbaPassword" $dbaPassword }}
  # $.dbaPassword: {{- $.dbaPassword }}
  {{- $monitoringPassword := randAlphaNum 30 | b64enc }}
  {{- $_ := set $ "monitoringPassword" $monitoringPassword }}
  # $.monitoringPassword: {{- $.monitoringPassword }}
  dbaPassword: {{ $dbaPassword }}
  monitoringPassword: {{ $monitoringPassword }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-cluster-demo.fullname" . }}-keys
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{- $name := printf "%s-keys" ( include "mongodb-cluster-demo.fullname" . ) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace $name).data }}
  {{- if $secret }}
  # Secret exists: 
  {{- toYaml $secret | nindent 2 }}
  {{ else }}
  key1: {{ randAlphaNum 756 | b64enc }}
  {{- end }}