apiVersion: v1
kind: Service
metadata:
  name: "{{ include "mongodb-cluster-demo.fullname" . }}-routersvc"
  labels:
    {{- include "mongodb-cluster-demo.labels" . | nindent 4 }}
    role: mongo-router
spec:
  clusterIP: None
  type: {{ .Values.service.router.type }}
  ports:
    - name: {{ .Values.service.router.ports.name }}
      port: {{ .Values.service.router.ports.port }}
      targetPort: {{ .Values.service.router.ports.port }}
      protocol: TCP

  selector:
    {{- include "mongodb-cluster-demo.labels" . | nindent 4 }}
    role: mongo-router
