---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: allow-pod-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-pod-list-sa
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: allow-pod-list
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: allow-pod-svc-ep-list
rules:
- apiGroups: [""]
  resources: ["pods","services","endpoints"]
  verbs: ["get", "list","watch"]
---
# workaround for microk8s and prometheus operator
# error was : Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list resource \"services\" in API group \"\" in the namespace \"mongodb\"
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-pod-svc-ep-list-prometheus
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: {{ .Values.serviceMonitor.namespace }}
roleRef:
  kind: Role
  name: allow-pod-svc-ep-list
  apiGroup: rbac.authorization.k8s.io