apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "mongodb-cluster-demo.fullname" . }}-router"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb-cluster-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mongodb-cluster-demo.labels" . | nindent 6 }}
      role: mongo-router
  serviceName: "{{ include "mongodb-cluster-demo.fullname" . }}-routersvc"
  replicas: {{ .Values.replicas.router.count }}
  template:
    metadata:
      labels:
        {{- include "mongodb-cluster-demo.labels" . | nindent 8 }}
        role: mongo-router
        app: mongo
      {{- if not .Values.serviceMonitor.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "metrics"
      {{- end }}
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      terminationGracePeriodSeconds: 30
      {{- $nodes := (lookup "v1" "Node" "" "").items }}
      {{- if $nodes }}
      #Nodes count: {{- len $nodes }} ; minAvailable.router: {{- .Values.minAvailable.router }}; Replicas: {{- .Values.replicas.router.count }}
        {{- if gt (len $nodes | int) (.Values.minAvailable.router | int) }}
          {{- if gt (len $nodes | int) (.Values.replicas.router.count | int) }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: 'app.kubernetes.io/name'
                operator: In
                values:
                - "{{ include "mongodb-cluster-demo.name" . }}"
              - key: 'app.kubernetes.io/instance'
                operator: In
                values:
                - "{{ .Release.Name }}"
              - key: 'helm-revision'
                operator: In
                values:
                - "{{ .Release.Revision }}"
              - key: 'role'
                operator: In
                values:
                - "mongo-router"
            topologyKey: "kubernetes.io/hostname"
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: keyfiles
        secret:
            secretName: {{ include "mongodb-cluster-demo.fullname" . }}-keys
            defaultMode: 0644
            items:
            - key: key1
              path: keyfile
      initContainers:
      # - name: startup
      #   image: busybox:latest
      #   command:
      #     - sh
      #     - "-c"
      #     - |
      #       set -ex
      #       CFGLAST={{ include "mongodb-cluster-demo.fullname" $ }}-cfg-{{ ( sub 1 ( .Values.replicas.cfg.count | int64 ) ) | toString }}.{{ include "mongodb-cluster-demo.fullname" $ }}-cfgsvc.{{ $.Release.Namespace }}.svc.cluster.local
      #       ROUTERLAST={{ include "mongodb-cluster-demo.fullname" $ }}-router-{{ sub 1 ( .Values.replicas.router.count | int64 ) | toString }}.{{ include "mongodb-cluster-demo.fullname" $ }}-routersvc.{{ $.Release.Namespace }}.svc.cluster.local
      #       timeout 5m sh -c "until nc -z -w 1 $ROUTERLAST {{ .Values.service.router.ports.port }}; do (echo -n . ; sleep 1s); done; echo router-svc reached"
      #       timeout 5m sh -c "until nc -z -w 1 $CFGLAST {{ .Values.service.cfg.ports.port }}; do (echo -n . ; sleep 1s); done; echo cfg-svc reached"
      #   {{- range $i, $e := until ($.Values.shardsCount | int) }}
      #       DBLAST={{ include "mongodb-cluster-demo.fullname" $ }}-shard{{ $i }}-db-{{ ( sub 1 ( $.Values.replicas.db.count | int64 ) ) | toString }}.{{ include "mongodb-cluster-demo.fullname" $ }}-shard{{ $i }}-dbsvc.{{ $.Release.Namespace }}.svc.cluster.local
      #       timeout 5m sh -c "until nc -z -w 1 $DBLAST {{ $.Values.service.db.ports.port }}; do (echo -n _ ; sleep 1s); done; echo db-svc {{ $i }} reached"
      #   {{- end }}
      - name: mongo-pwd
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        image: "{{ $.Values.image.repository }}:{{ $.Chart.AppVersion }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command:
          - 'bash'
          - '-c'
          - |
            set -ex
            USERNAME={{ $.Values.clstAdminName }}
            set +x
            USERPASS="$ADM_PASS"
            set -ex
            echo "app started at $(date -u)"
            echo "{{ .Values.replicas.router.count | int64 }}={{ sub ( .Values.replicas.router.count | int64 ) 1 | toString }};{{ .Values.replicas.cfg.count | int64  }}={{ ( sub ( .Values.replicas.cfg.count | int64 ) 1 ) | toString }};{{ .Values.replicas.db.count }}={{ sub ( $.Values.replicas.db.count | int64 ) 1 | toString }}"
            if [ "${MY_POD_NAME//*-}" == "0" ] ; then
              which nc || apt update && apt install -y netcat
              CFGLAST={{ include "mongodb-cluster-demo.fullname" $ }}-cfg-{{ ( sub ( .Values.replicas.cfg.count | int64 ) 1 ) | toString }}.{{ include "mongodb-cluster-demo.fullname" $ }}-cfgsvc.{{ $.Release.Namespace }}.svc.cluster.local
              timeout 5m sh -c "until nc -z -w 1 $CFGLAST {{ .Values.service.cfg.ports.port }}; do (echo -n . ; sleep 1s); done; echo cfg-svc reached"
          {{- range $i, $e := until ($.Values.shardsCount | int) }}
              DBLAST={{ include "mongodb-cluster-demo.fullname" $ }}-shard{{ $i }}-db-{{ ( sub ( $.Values.replicas.db.count | int64 ) 1 ) | toString }}.{{ include "mongodb-cluster-demo.fullname" $ }}-shard{{ $i }}-dbsvc.{{ $.Release.Namespace }}.svc.cluster.local
              timeout 5m sh -c "until nc -z -w 1 $DBLAST {{ $.Values.service.db.ports.port }}; do (echo -n _ ; sleep 1s); done; echo db-svc {{ $i }} reached"
          {{- end }}
              CFGSVC={{ include "mongodb-cluster-demo.fullname" $ }}-cfgsvc.{{ $.Release.Namespace }}.svc.cluster.local
              #timeout 5m sh -c "until ( echo $(mongo mongodb://$USERNAME:$USERPASS@$CFGSVC:{{ .Values.service.cfg.ports.port }} --quiet --eval 'rs.status().ok') | fgrep 1 ) ; do (echo -n . ; sleep 2s); done; echo cfg-svc rs.status good"
              #mongo mongodb://$USERNAME:$USERPASS@$CFGSVC:{{ .Values.service.cfg.ports.port }} --quiet --eval 'rs.status()'
            {{- range $i, $e := until ($.Values.shardsCount | int) }}
              DBSVC={{ include "mongodb-cluster-demo.fullname" $ }}-shard{{ $i }}-dbsvc.{{ $.Release.Namespace }}.svc.cluster.local
              #timeout 5m sh -c "until ( echo $(mongo mongodb://$USERNAME:$USERPASS@$DBSVC:{{ $.Values.service.db.ports.port }} --quiet --eval 'rs.status().ok') | fgrep 1 ) ; do (echo -n _ ; sleep 2s); done; echo shard{{ $i }}-svc rs.status good"
              #mongo mongodb://$USERNAME:$USERPASS@$DBSVC:{{ $.Values.service.db.ports.port }} --quiet --eval 'rs.status()'
            {{- end }}
              cp /secret/keyfile /tmp/keyfile
              chmod 400 /tmp/keyfile
              mongos --configdb {{ include "mongodb-cluster-demo.configstr" . }} --bind_ip 127.0.0.1 --port {{ $.Values.service.router.ports.port }} --keyFile=/tmp/keyfile &
              sleep 1s
              HOST='127.0.0.1'
              timeout 15s sh -c "until nc -z -w 1 $HOST {{ .Values.service.router.ports.port }}; do (echo -n . ; sleep 1s); done; echo router-svc reached"
              CONNSTR="mongodb://$USERNAME:$USERPASS@$HOST:{{ $.Values.service.router.ports.port }}/admin"
              RES=$(mongo $CONNSTR --quiet --eval 'db.getUsers();')
              if [ ! "$(echo $RES | fgrep -c "admin.$USERNAME" )" == 1 ] ; then
                mongo $CONNSTR --quiet --eval "db.createUser( { user: \"$USERNAME\", pwd: \"$USERPASS\", roles: [ { role: \"root\", db: \"admin\" } ], \"mechanisms\": [ \"SCRAM-SHA-256\" ] } );"
              else
                echo $RES
              fi
              USERNAME={{ $.Values.exporterUserName }}
              USERPASS="$MONITORING_PASS"
              if [ ! "$(echo $RES | fgrep -c "admin.$USERNAME" )" == 1 ] ; then
                mongo $CONNSTR --quiet --eval "db.createUser( { user: \"$USERNAME\", pwd: \"$USERPASS\", roles: [ { role: \"clusterMonitor\", db: \"admin\" }, { role: \"read\", db: \"local\" } ], \"mechanisms\": [ \"SCRAM-SHA-256\" ] } );"
              else
                echo $RES
              fi
              kill $(pgrep mongos)
              timeout 30s sh -c 'while ( pgrep mongos > /dev/null ) ; do (echo -n . ; sleep 1s); done; echo finished'
            fi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ADM_PASS
            valueFrom:
              secretKeyRef:
                name: "{{ include "mongodb-cluster-demo.fullname" $ }}-dbsecrets"
                key: dbaPassword
          - name: MONITORING_PASS
            valueFrom:
              secretKeyRef:
                name: "{{ include "mongodb-cluster-demo.fullname" $ }}-dbsecrets"
                key: monitoringPassword
        volumeMounts:
          - name: keyfiles
            mountPath: /secret/keyfile
            subPath: keyfile
            readOnly: true
      containers:
      - name: mongo
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: keyfiles
            mountPath: /secret/keyfile
            subPath: keyfile
            readOnly: true
        command:
          - 'bash'
          - '-c'
          - |
            ps aux
            id
            ls -l /data
            ls -l /secret/keyfile
            cp /secret/keyfile /tmp/keyfile
            chmod 400 /tmp/keyfile
            ls -l /tmp/keyfile
            mongos --configdb {{ include "mongodb-cluster-demo.configstr" . }} --bind_ip_all --port {{ $.Values.service.router.ports.port }} --keyFile=/tmp/keyfile
            EXCODE="$?"
            echo "app finished at $(date -u)" | tee -a /tmp/prestop.log
            echo "app finished, result code: $EXCODE"
            echo
            echo "Container lifecycle logged events:"
            echo
            cat /tmp/prestop.log
        lifecycle:
          preStop:
            exec:
              command: 
                - "/bin/bash"
                - "-c"
                - |
                  echo 'lyfecycle preStop hook: Pod is set to the “Terminating” State, pause 5s and send SIGINT to dotnet' >> /tmp/prestop.log
                  echo "sleep 3s since $(date -u)" >> /tmp/prestop.log
                  sleep 3s
                  echo "preStop will shutdown mongos now at $(date -u)" >> /tmp/prestop.log
                  mongo mongodb://127.0.0.1:27017/admin --quiet --eval "db.shutdownServer();"
        env:
          - name: "SHARD_COUNT"
            value: "{{ .Values.shardsCount }}"
        {{- range $i, $e := until ( .Values.shardsCount | int) }}
        {{- $_ := set $ "shardIndex" $i }}
          - name: "SHARD{{ $i }}_RS"
            value: "{{ include "mongodb-cluster-demo.dbstr" $ }}"
        {{- end }}
        ports:
          - name: router
            containerPort: {{ .Values.service.router.ports.port }}
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.router.ports.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.router.ports.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: mongodb-exporter
        env:
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "mongodb-cluster-demo.fullname" $ }}-dbsecrets"
                key: monitoringPassword
          - name: MONGODB_URI
            value: "mongodb://{{ $.Values.exporterUserName }}:$MONGODB_PASSWORD@127.0.0.1:{{ $.Values.service.router.ports.port }}"
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        {{- end }}
        image: "{{ .Values.exporter_image.repository }}:{{ .Values.exporter_image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --web.listen-address={{ printf ":%s" .Values.exporter_port }}
        {{- toYaml .Values.extraArgs | nindent 8 }}
        ports:
        - name: metrics
          containerPort: {{ .Values.exporter_port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
